ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np

In [2]:
x=np.array([2,3,4])

In [3]:
x

array([2, 3, 4])

In [5]:
zero_vector=np.zeros(5)

In [6]:
zero_vector

array([0., 0., 0., 0., 0.])

In [7]:
zero_matrix=np.zeros((5,3))

In [11]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
Y=np.array([[3,4,5],[7,8,9],[3,3,3]])

In [16]:
Y

array([[3, 4, 5],
       [7, 8, 9],
       [3, 3, 3]])

In [3]:
# Access and slice numpy arrays
x=np.array([3,4,6])

In [4]:
y=np.array([2,8,4])

In [5]:
z=x+y

In [6]:
z

array([ 5, 12, 10])

In [7]:
x[2]

6

In [9]:
x[0:2]

array([3, 4])

In [10]:
X=np.array([[2,3,7],[3,8,7]])

In [12]:
X[:,0]

array([2, 3])

In [13]:
Y=np.array([[3,8,1],[1,9,4]])

In [15]:
X[:,0]+Y[:,2]

array([3, 7])

In [16]:
X[1][1]

8

In [17]:
X[1,:]

array([3, 8, 7])

In [2]:
G1=np.array([2,3,4,5,6,7,8])

In [3]:
G1<5

array([ True,  True,  True, False, False, False, False])

In [4]:
G1[G1<5]

array([2, 3, 4])

In [5]:
G2[G1<5]

NameError: name 'G2' is not defined

In [10]:
G2=np.array([4,5,6,7,8,9,10])

In [11]:
G2[G1>5]

array([ 8,  9, 10])

In [12]:
ind=G1>5

In [13]:
G1[ind]

array([6, 7, 8])

In [14]:
z1=G1[0:3]

In [15]:
z1

array([2, 3, 4])

In [16]:
z1[0]=3

In [17]:
z1

array([3, 3, 4])

In [18]:
G1

array([3, 3, 4, 5, 6, 7, 8])

In [19]:
#Slicing chages the original loop but numpy indexing do not change the original list

In [20]:
G1[0]=1

In [21]:
G1

array([1, 3, 4, 5, 6, 7, 8])

In [22]:
ind=G1<5

In [23]:
ind

array([ True,  True,  True, False, False, False, False])

In [24]:
z1=G1[ind]

In [25]:
z1

array([1, 3, 4])

In [28]:
z1[0]=3

In [29]:
z1

array([3, 3, 4])

In [30]:
G1

array([1, 3, 4, 5, 6, 7, 8])

In [5]:
x=np.linspace(0,100,11)

In [6]:
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [9]:
x=np.logspace(1,2,10)

In [10]:
x

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [11]:
y=np.logspace(np.log10(250),np.log10(500),10)

In [12]:
y

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [13]:
Y=np.random.random(10)

In [14]:
Y

array([4.61218990e-01, 6.48532332e-01, 8.26956496e-01, 4.42534824e-01,
       5.78158434e-01, 8.68286886e-01, 2.64422104e-01, 5.20027457e-01,
       1.11782829e-06, 7.43992492e-02])

In [17]:
np.any(Y<0.9)

True

In [18]:
np.all(Y>=0.1)

False

In [19]:
Y

array([4.61218990e-01, 6.48532332e-01, 8.26956496e-01, 4.42534824e-01,
       5.78158434e-01, 8.68286886e-01, 2.64422104e-01, 5.20027457e-01,
       1.11782829e-06, 7.43992492e-02])

In [24]:
X=np.array([[2,3,4], [5,8,9]])

In [25]:
X.size

6

In [26]:
X.shape

(2, 3)