In [1]:
import numpy as np  
a=np.arange(12) 

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b=np.where([[True, False], [True, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])  

In [5]:
b

array([[1, 8],
       [3, 4]])

In [15]:
import numpy as np
import random
def create_board():
    X=np.zeros((3,3),dtype=int)
    return X
create_board()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
def place(board, player, position):
    if board[position] == 0:
        board[position] = player
        return board

board = create_board()
place(board, 1, (0, 0))

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
def possibilities(board):
    a = np.where(board == 0)
    return a

In [41]:
random.seed(1)

def random_place(board, player):
    selections = possibilities(board)
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
    return board

random_place(board, 0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
selections = possibilities(board)

In [32]:
len(selections)

2

In [38]:
if len(selections) > 0:
        selection = random.choice(selections)
        #place(board, player, selection)
selection

array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64)